# Generated by Django 4.0.4 on 2022-09-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_first_name_customer_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='i_am',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='looking_for',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
