# Generated by Django 4.0.4 on 2022-09-15 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
