# Generated by Django 4.0.4 on 2022-09-15 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customer_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='liked_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
