# Generated by Django 4.0.4 on 2022-09-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_customer_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
