# Generated by Django 4.0.4 on 2022-09-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customer_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='liked_by',
        ),
    ]
