# Generated by Django 4.1.1 on 2022-10-04 11:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0011_remove_customer_liked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="about",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="about"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="hair_color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="height",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="languages",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="mobile_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, unique=True
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="sexual_orientation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="weight",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
