# Generated by Django 4.1.1 on 2022-10-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0013_adminpanelrequests_customerimage_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdminPanelRequests", new_name="AdminPanelRequest",
        ),
    ]
