# Generated by Django 4.0.4 on 2022-09-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_pagedata_options_pagedata_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedata',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
