# Generated by Django 4.0.4 on 2022-09-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_like_read_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='match',
            field=models.BooleanField(default=False),
        ),
    ]
