# Generated by Django 4.0.4 on 2022-09-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_like_match_review_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='match',
        ),
        migrations.RemoveField(
            model_name='review',
            name='match',
        ),
    ]
